"""Core configuration package"""
from app.core.config import (
    BASE_DIR,
    UPLOADS_DIR,
    RAW_IMAGES_DIR,
    RESULT_IMAGES_DIR,
    HEATMAPS_DIR,
    WEIGHTS_DIR,
    DEFAULT_MODEL_WEIGHTS,
    DEFAULT_MEDICAL_DISCLAIMER,
    APP_TITLE,
    APP_DESCRIPTION,
    APP_VERSION,
)

__all__ = [
    "BASE_DIR",
    "UPLOADS_DIR",
    "RAW_IMAGES_DIR",
    "RESULT_IMAGES_DIR",
    "HEATMAPS_DIR",
    "WEIGHTS_DIR",
    "DEFAULT_MODEL_WEIGHTS",
    "DEFAULT_MEDICAL_DISCLAIMER",
    "APP_TITLE",
    "APP_DESCRIPTION",
    "APP_VERSION",
]
